version: "3.3"
services:
  redis:
    image: redis:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:9628:6379"
  mysql:
    image: mysql:5.7
    platform: linux/amd64
    ports:
      - "127.0.0.1:9629:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: app
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  unfazed:
    build: .
    ports:
      - "127.0.0.1:9627:9527"
    depends_on:
      - redis
      - mysql
    command: tail -f /src/Dockerfile
    volumes:
      - .:/src